
import React, { useState, useMemo } from 'react';

type Tab = 'login' | 'logout';

const generateLoginScript = (apiKey: string, sender: string, receiver: string, routerName: string): string => `
# MikroTik Script for PPPoE On-Up Event (User Login)
# Generated by Notifier Script Generator

# --- SCRIPT START ---
{
    :log info "PPPoE user $user logged in, executing WhatsApp notification script...";
    
    # Get current date and time
    :local date [/system clock get date];
    :local time [/system clock get time];

    # Get total active PPPoE users
    :local totalActive [/ppp active print count-only];

    # --- User Configurable Variables ---
    :local apiKey "${apiKey}";
    :local senderNumber "${sender}";
    :local receiverNumber "${receiver}";
    :local routerName "${routerName}";
    # --- End of User Configurable Variables ---

    # Construct the message payload
    :local message "✅ *PPPoE LOGIN*%0A%0A";
    :set message ($message . "Router: *" . $routerName . "*%0A");
    :set message ($message . "Tanggal: " . $date . "%0A");
    :set message ($message . "Jam: " . $time . "%0A");
    :set message ($message . "User: " . $user . "%0A");
    :set message ($message . "IP Client: " . $"remote-address" . "%0A");
    :set message ($message . "Caller ID: " . $"caller-id" . "%0A");
    :set message ($message . "Uptime: 00:00:00%0A");
    :set message ($message . "Total Active: " . $totalActive . " Client%0A");
    :set message ($message . "Service: " . $service . "%0A");
    :set message ($message . "Last Disconnect Reason: " . $cause . "%0A");
    :set message ($message . "Last Logout: " . $"last-logged-out");

    # Construct the API URL
    :local url "https://wa.vpnjombang.my.id/send-message";
    :set url ($url . "?api_key=" . $apiKey);
    :set url ($url . "&sender=" . $senderNumber);
    :set url ($url . "&number=" . $receiverNumber);
    :set url ($url . "&message=" . [:url-encode $message]);

    # Send the request
    /tool fetch url=$url keep-result=no;
    :log info "WhatsApp notification sent for user $user.";
}
# --- SCRIPT END ---
`.trim();

const generateLogoutScript = (apiKey: string, sender: string, receiver: string, routerName: string): string => `
# MikroTik Script for PPPoE On-Down Event (User Logout)
# Generated by Notifier Script Generator

# --- SCRIPT START ---
{
    :log info "PPPoE user $user logged out, executing WhatsApp notification script...";

    # Get current date and time
    :local date [/system clock get date];
    :local time [/system clock get time];

    # Get total active PPPoE users (user has already logged out, so current count is accurate)
    :local totalActive [/ppp active print count-only];

    # --- User Configurable Variables ---
    :local apiKey "${apiKey}";
    :local senderNumber "${sender}";
    :local receiverNumber "${receiver}";
    :local routerName "${routerName}";
    # --- End of User Configurable Variables ---

    # Construct the message payload
    :local message "❌ *PPPOE-LOGOUT*%0A%0A";
    :set message ($message . "Router: *" . $routerName . "*%0A");
    :set message ($message . "Tanggal: " . $date . "%0A");
    :set message ($message . "Jam: " . $time . "%0A");
    :set message ($message . "USER: " . $user . "%0A");
    :set message ($message . "Last Disconnect Reason: " . $cause . "%0A");
    :set message ($message . "Last Logout: " . $date . " " . $time . "%0A");
    :set message ($message . "Last Caller ID: " . $"caller-id" . "%0A");
    :set message ($message . "Total active: " . $totalActive . " Client");

    # Construct the API URL
    :local url "https://wa.vpnjombang.my.id/send-message";
    :set url ($url . "?api_key=" . $apiKey);
    :set url ($url . "&sender=" . $senderNumber);
    :set url ($url . "&number=" . $receiverNumber);
    :set url ($url . "&message=" . [:url-encode $message]);

    # Send the request
    /tool fetch url=$url keep-result=no;
    :log info "WhatsApp notification sent for user $user.";
}
# --- SCRIPT END ---
`.trim();

const loginPreviewTemplate = `✅ *PPPoE LOGIN*

Router: *{routerName}*
Tanggal: {date}
Jam: {time}
User: pppoe-user-01
IP Client: 10.0.0.123
Caller ID: 00:11:22:33:44:55
Uptime: 00:00:00
Total Active: 105 Client
Service: pppoe-profile
Last Disconnect Reason: user-request
Last Logout: {date} {time}`;

const logoutPreviewTemplate = `❌ *PPPOE-LOGOUT*

Router: *{routerName}*
Tanggal: {date}
Jam: {time}
USER: pppoe-user-01
Last Disconnect Reason: peer-request
Last Logout: {date} {time}
Last Caller ID: 00:11:22:33:44:55
Total active: 104 Client`;

const formatPreview = (template: string, routerName: string): string => {
    const now = new Date();
    const date = `jan/${now.getDate()}/${now.getFullYear()}`;
    const time = now.toLocaleTimeString('en-GB');
    return template
        .replace(/{routerName}/g, routerName || 'MyRouter')
        .replace(/{date}/g, date)
        .replace(/{time}/g, time);
};

interface InputFieldProps {
    label: string;
    id: string;
    value: string;
    onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    placeholder: string;
    type?: string;
}

const InputField: React.FC<InputFieldProps> = ({ label, id, value, onChange, placeholder, type = 'text' }) => (
    <div>
        <label htmlFor={id} className="block text-sm font-medium text-gray-400 mb-2">
            {label}
        </label>
        <input
            type={type}
            id={id}
            name={id}
            value={value}
            onChange={onChange}
            placeholder={placeholder}
            className="w-full bg-gray-800 border border-gray-600 rounded-lg px-4 py-2 text-gray-200 focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-all duration-200"
        />
    </div>
);


interface ScriptDisplayProps {
    script: string;
}

const ScriptDisplay: React.FC<ScriptDisplayProps> = ({ script }) => {
    const [isCopied, setIsCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(script).then(() => {
            setIsCopied(true);
            setTimeout(() => setIsCopied(false), 2000);
        });
    };

    return (
        <div className="bg-gray-800/50 rounded-xl shadow-lg relative h-full flex flex-col">
            <div className="flex justify-between items-center p-4 border-b border-gray-700">
                <h3 className="font-semibold text-lg text-white">Generated Script</h3>
                <button
                    onClick={handleCopy}
                    className="flex items-center gap-2 bg-cyan-600 hover:bg-cyan-700 disabled:bg-gray-500 text-white font-bold py-2 px-4 rounded-lg transition-colors duration-200"
                >
                    {isCopied ? (
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                    ) : (
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                        </svg>
                    )}
                    {isCopied ? 'Copied!' : 'Copy'}
                </button>
            </div>
            <pre className="p-4 text-sm whitespace-pre-wrap overflow-auto flex-grow text-cyan-300 font-mono">
                <code>{script}</code>
            </pre>
        </div>
    );
};


interface MessagePreviewProps {
    message: string;
    type: Tab;
}

const MessagePreview: React.FC<MessagePreviewProps> = ({ message, type }) => {
    return (
        <div className="bg-gray-800/50 rounded-xl shadow-lg h-full flex flex-col">
             <div className="flex justify-between items-center p-4 border-b border-gray-700">
                <h3 className="font-semibold text-lg text-white">Message Preview</h3>
             </div>
             <div className="p-4 flex-grow bg-cover bg-center" style={{backgroundImage: "url('https://i.pinimg.com/736x/8c/98/99/8c98994518b575bfd8c949e91d20548b.jpg')"}}>
                <div className={`max-w-xs ${type === 'login' ? 'ml-auto' : 'mr-auto'} p-3 rounded-lg shadow-md whitespace-pre-wrap text-sm text-left ${type === 'login' ? 'bg-[#075e54] text-white rounded-tr-none' : 'bg-[#202c33] text-white rounded-tl-none'}`}>
                    {message}
                </div>
            </div>
        </div>
    );
};


const App: React.FC = () => {
    const [apiKey, setApiKey] = useState('');
    const [sender, setSender] = useState('');
    const [receiver, setReceiver] = useState('');
    const [routerName, setRouterName] = useState('MyRouter');
    const [activeTab, setActiveTab] = useState<Tab>('login');

    const loginScript = useMemo(() => generateLoginScript(apiKey, sender, receiver, routerName), [apiKey, sender, receiver, routerName]);
    const logoutScript = useMemo(() => generateLogoutScript(apiKey, sender, receiver, routerName), [apiKey, sender, receiver, routerName]);

    const loginPreview = useMemo(() => formatPreview(loginPreviewTemplate, routerName), [routerName]);
    const logoutPreview = useMemo(() => formatPreview(logoutPreviewTemplate, routerName), [routerName]);
    
    const isFormIncomplete = !apiKey || !sender || !receiver || !routerName;

    return (
        <div className="min-h-screen bg-gray-900 font-sans p-4 sm:p-6 lg:p-8">
            <div className="max-w-7xl mx-auto">
                <header className="text-center mb-10">
                    <h1 className="text-4xl sm:text-5xl font-extrabold text-white tracking-tight">MikroTik WhatsApp Notifier</h1>
                    <p className="mt-4 text-lg text-gray-400 max-w-2xl mx-auto">Generate scripts to send PPPoE login/logout notifications via WhatsApp.</p>
                </header>

                <main className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Left Column: Configuration & Instructions */}
                    <div className="space-y-8">
                        <div className="bg-gray-800/50 rounded-xl shadow-lg p-6">
                            <h2 className="text-2xl font-bold text-white mb-6 border-b border-gray-700 pb-4">Configuration</h2>
                            <div className="space-y-4">
                                <InputField label="WhatsApp API Key" id="apiKey" value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder="Enter your API key" />
                                <InputField label="Sender Number" id="sender" value={sender} onChange={e => setSender(e.target.value)} placeholder="e.g., 628xxxx" />
                                <InputField label="Receiver Number" id="receiver" value={receiver} onChange={e => setReceiver(e.target.value)} placeholder="e.g., 628xxxx or group ID" />
                                <InputField label="Router Name / Identifier" id="routerName" value={routerName} onChange={e => setRouterName(e.target.value)} placeholder="e.g., Router-Office" />
                            </div>
                        </div>

                        <div className="bg-gray-800/50 rounded-xl shadow-lg p-6">
                            <h2 className="text-2xl font-bold text-white mb-4 border-b border-gray-700 pb-4">How to Use</h2>
                            <ol className="list-decimal list-inside space-y-3 text-gray-300">
                                <li>Fill in all the configuration fields above.</li>
                                <li>Select the "On Login" or "On Logout" tab.</li>
                                <li>Click the "Copy" button to copy the generated script.</li>
                                <li>In your MikroTik router (using WinBox or WebFig):</li>
                                <li className="ml-4">Go to <code className="bg-gray-900 px-1 rounded">PPP</code> -&gt; <code className="bg-gray-900 px-1 rounded">Profiles</code>.</li>
                                <li className="ml-4">Open the profile your PPPoE users are using.</li>
                                <li className="ml-4">Go to the <code className="bg-gray-900 px-1 rounded">Scripts</code> tab.</li>
                                <li className="ml-4">Paste the "On Login" script into the <code className="bg-gray-900 px-1 rounded">On Up</code> field.</li>
                                <li className="ml-4">Paste the "On Logout" script into the <code className="bg-gray-900 px-1 rounded">On Down</code> field.</li>
                                <li>Click "Apply" and "OK". Notifications will now be sent!</li>
                            </ol>
                        </div>
                    </div>

                    {/* Right Column: Scripts & Previews */}
                    <div className="flex flex-col gap-8">
                         <div className="flex-shrink-0">
                            <div className="border-b border-gray-700">
                                <nav className="-mb-px flex space-x-4" aria-label="Tabs">
                                    <button onClick={() => setActiveTab('login')} className={`${activeTab === 'login' ? 'border-cyan-500 text-cyan-400' : 'border-transparent text-gray-400 hover:text-gray-200 hover:border-gray-500'} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-lg transition-colors`}>
                                        On Login Script
                                    </button>
                                    <button onClick={() => setActiveTab('logout')} className={`${activeTab === 'logout' ? 'border-cyan-500 text-cyan-400' : 'border-transparent text-gray-400 hover:text-gray-200 hover:border-gray-500'} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-lg transition-colors`}>
                                        On Logout Script
                                    </button>
                                </nav>
                            </div>
                        </div>
                        
                        {isFormIncomplete ? (
                           <div className="flex-grow flex items-center justify-center bg-gray-800/50 rounded-xl p-8 text-center">
                                <div className="max-w-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="mx-auto h-12 w-12 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                    </svg>
                                    <h3 className="mt-2 text-lg font-medium text-white">Complete Configuration</h3>
                                    <p className="mt-1 text-sm text-gray-400">Please fill in all fields on the left to generate the scripts and see previews.</p>
                                </div>
                           </div>
                        ) : (
                            <div className="grid grid-cols-1 xl:grid-cols-2 gap-8 flex-grow">
                                {activeTab === 'login' ? (
                                    <>
                                        <ScriptDisplay script={loginScript} />
                                        <MessagePreview message={loginPreview} type="login" />
                                    </>
                                ) : (
                                    <>
                                        <ScriptDisplay script={logoutScript} />
                                        <MessagePreview message={logoutPreview} type="logout" />
                                    </>
                                )}
                            </div>
                        )}
                    </div>
                </main>
            </div>
        </div>
    );
};

export default App;
